export const disscussionData = [
    {
        'name':'Bandhan Bank Ltd.',
        'description':'Axis Bank stops redemption of credit card reward points earned by these customers; asks for proof of usage',
        'sector':1,
        'like':'2k',
        'views':'2k',
        'comment':'2k',
        'time':'20m ago',
    },
    {
        'name':'Kotak Mahindra Bank',
        'description':'Adani Power, Paytm, Infosys & Kotak Bank: What Osho Krishan of Angel One says on these 4 stocks',
        'sector':1,
        'like':'1k',
        'views':'2.2k',
        'comment':'570',
        'time':'8h ago',
    },
    {
        'name':'HDFC Bank Ltd.',
        'description':'HDFC AMC, Nippon AMC: AMC stocks in focus as MFs start releasing stress test results',
        'sector':2,
        'like':'1.6k',
        'views':'5k',
        'comment':'2k',
        'time':'12h ago',
    },
    {
        'name':'HDFC Bank Ltd.',
        'description':'HDFC AMC, Nippon AMC: AMC stocks in focus as MFs start releasing stress test results',
        'sector':3,
        'like':'122',
        'views':'1k',
        'comment':'22',
        'time':'1d ago',
    },
    {
        'name':'ICICI Bank Ltd.',
        'description':'Stock recommendations by analysts for March 15: Asian Paints, BEL and ICICI Bank',
        'sector':3,
        'like':'0',
        'views':'10',
        'comment':'1',
        'time':'2d ago',
    },
    {
        'name':'HDFC Bank Ltd.',
        'description':'HDFC AMC, Nippon AMC: AMC stocks in focus as MFs start releasing stress test results',
        'sector':4,
        'like':'732',
        'views':'4.5k',
        'comment':'292',
        'time':'4d ago',
    },
    {
        'name':'Bandhan Bank Ltd.',
        'description':'Axis Bank stops redemption of credit card reward points earned by these customers; asks for proof of usage',
        'sector':4,
        'like':'873',
        'views':'2k',
        'comment':'559k',
        'time':'10d ago',
    },
]