import { Inter } from "next/font/google";
import "./globals.css";
import Slider from "@/components/Slider";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Go India Stock",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} grid grid-cols-7 gap-2`} >
        <Slider />
        <div></div>
        {children}
      </body>
    </html>
  );
}
